server:
  port: 9527

wx:
  token: 微信自动回复的token

openAI:
  token: chatgpt的token

file:
  upload:
    containerpath: 文件挂载到容器的位置
    systempath: 文件存放位置
    hostname: 域名
    username: 服务器账户
    password: 服务器密码
